# UI STRINGS
EXE_NAME = "wrecks-ui-manager"

TITLE_EXPORTER = "UI EXPORTER"
TITLE_IMPORTER = "UI IMPORTER"

BTN_EXPORT_TXT = "EXPORT"

LABEL_SELECT_VERSION = "Select your WoW Version"
LABEL_SELECT_ACCOUNT = "Select your Account"
LABEL_SELECT_REALM = "Select your Realm"
LABEL_SELECT_CHAR = "Select your Character"

LABEL_CHECKBOX = "Include ICONS"
